### ISSUE TITLE
Toots not posting with privacy "unlisted" and hashtags

### ISSUE THREAD

**Issue by rocket357** [muesli/telephant#10]
Ok, so the combination of hashtag + unlisted privacy makes no sense, but I stumbled across this behavior accidentally.

Steps to reproduce:

1) Hit New Post button.
2) Enter "#test"
3) Click Post.

If privacy is set to "unlisted" by default, the toot will not post.  Bringing up the New Post window again shows the same contents as before ("#test").

**Comment by rocket357** [comment]
Nevermind, not related to hashtags.  Seems to occur without hashtags as well.

**Comment by muesli** [comment]
So it's only related to the privacy setting?

**Comment by rocket357** [comment]
Doesn't seem to matter which privacy setting is in use.

**Comment by muesli** [comment]
Which instance are you trying that with?

**Comment by rocket357** [comment]
@rocket357@bsd.network

**Comment by muesli** [comment]
Thanks for the report! Managed to identify and fix the issue. Pushed to master and uploaded new pre-0.1 releases.
