### ISSUE TITLE
replying to a thread you last tooted in only mentions/dms yourself

### ISSUE THREAD

**Issue by Notsonoble** [muesli/telephant#11]
Behavior:
Clicking on a toot in a thread that you were the last toot in only mentions yourself.

Expected behavior:
Should also grab those mentioned in toot you're replying too.

Muesli:
Mentioned this already from my niu.moe account, but thought'd be better to have an issue here for tracking purposes. Also, maybe this is intended; it just isn't how the web interface or any other client's I've used behave. If so feel free to close issue

**Comment by muesli** [comment]
Fixed by eb387a1.
