### ISSUE TITLE
Opening a toot and closing it, breaks scrolling with scrollwheel

### ISSUE THREAD

**Issue by Zatnosk** [muesli/telephant#18]
When I click on a toot to read the conversation, and then click beside it to close it again, I lose the ability to scroll using the mouse wheel. The scrollbars still work fine, although scrolling is a bit janky when dragging them.

**Comment by muesli** [comment]
Thanks for the report!

Which platform is that on? Are you using one of the binaries I provided or did you compile it yourself? Note that I regularly keep updating the builds on GitHub, so maybe try downloading the latest build there to see if the issue persists.

**Comment by Zatnosk** [comment]
It's on Linux 64bit. I downloaded the binary, and then compiled it myself too. I think it was a problem in both, but at least in the self-compiled.

**Comment by CalmBit** [comment]
Not able to confirm this on MacOS - possibly a Linux only bug?

(don't have a Linux machine to work with, unfortunately 😞

**Comment by muesli** [comment]
Haven't been able to reproduce this on Linux either.

@Zatnosk Can you check if this issue persists in the latest binaries?

**Comment by Zatnosk** [comment]
I just tried to confirm it in the same binary, and there's no problem now. It seems like it was a problem with my computer, somehow?

**Comment by muesli** [comment]
@Zatnosk Thanks for trying to reproduce it once more! I'm going to close this issue, but please, should you ever be able to trigger it again, don't hesitate to let us know, so we can re-open it and try to investigate some more.
