### ISSUE TITLE
URLs are counted wrong for toot length

### ISSUE THREAD

**Issue by creideiki** [muesli/telephant#23]
Mastodon is supposed to [treat all links as 23 characters long](https://docs.joinmastodon.org/usage/basics/#text) when determining toot length, but Telephant [counts each character](https://github.com/muesli/telephant/blob/932a10e5db3b067b721f4bd881f80592e2bced10/qml/MessagePopup.qml#L57).

**Comment by muesli** [comment]
Fixed in master.
