### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by muesli** [muesli/telephant#29]
Show (desktop) notifications when certain events arrive.

**Comment by CalmBit** [comment]
Possibly with https://github.com/martinlindhe/notify?

Poring over QT documentation for a solution came up fruitless, so this might be the best way to handle it. I'd be willing to tackle it, if you'd like 😄

**Comment by muesli** [comment]
I got an implementation using beeep (https://github.com/gen2brain/beeep). Can commit that in a minute. Qt actually got pretty awesome notification support thanks to snorenotify.

**Comment by CalmBit** [comment]
Oh sweet! Good to see 😄

**Comment by muesli** [comment]
Added in 21b941d. It's not the best solution yet, as it doesn't display image data so far, and we'd need to strip the markup in the message body, should we want to display it.
