### ISSUE TITLE
Text Box Boundaries

### ISSUE THREAD

**Issue by phjlipp** [muesli/telephant#3]
When rezising the window too narrow horizontally, text boxes start exceeding their boundaries like seen [here](https://imgur.com/a/YAmR0)

**Comment by muesli** [comment]
Fixed in master.

**Comment by xantulon** [comment]
FYI I just downloaded telephant_0.1pre_Linux_64bit, on xubuntu 18.04 and I'm seeing the text overrun.

**Comment by muesli** [comment]
@xantulon Wondering, was it a huge link or got a screenshot by chance?

**Comment by xantulon** [comment]
It's the same one from Mastodon. For some reason I couldn't upload the screenshot here. Maybe because it's a closed bug report, or because I'd already uploaded it to a new issue when GitHub pointed out this issue, so I canceled it.
