### ISSUE TITLE
Support for content warnings

### ISSUE THREAD

**Issue by muesli** [muesli/telephant#33]
Support CWs and blur media.

**Comment by CalmBit** [comment]
Any progress on this, or could I try to tackle this?

**Comment by muesli** [comment]
Haven't started working on that - so absolutely, any contribution from you is always welcome! :heart_eyes: 

Let me know if you need any pointers or help finding your way through the code.

**Comment by CalmBit** [comment]
Absolutely! I'll keep you posted 😄

**Comment by muesli** [comment]
Added support for content warnings and spoiler texts in 7d57627. We should still look into image blurring as you suggested on IRC.
