### ISSUE TITLE
Doesn't display a window in Ubuntu

### ISSUE THREAD

**Issue by Yowlen** [muesli/telephant#42]
I'm not sure what the deal is, but I haven't been able to get Telephant to work since that first day when we did all that stuff figuring out the Ubuntu dependencies to get it working. There was a couple weeks in between that day and the next time I used it, so there's a decent time window in which things could've broken.

In regards to symptoms, the background process works fine, giving me system notifications for new mentions and stuff, but there's nothing in the foreground. No window or anything ever shows up. When launched outside the terminal, I have to kill it via the task manager. Luckily I can kill it with a simple CTRL-C in the terminal, though.

As for *how* it's broken, I'm not entirely sure. I don't know if the app simply doesn't update properly when I re-run the instructions or if the app actually broke.

I *am* getting an error message in the terminal, if it helps:
>QQmlApplicationEngine failed to load component
>qrc:/qml/telephant.qml:2 module "QtQuick.Controls" version 2.5 is not installed

Beyond that, I have nothing.

**Comment by muesli** [comment]
Ok, that means there's definitely still (one or more) packages missing. Can you try and "apt install qml-module-qtquick*"?

**Comment by Yowlen** [comment]
All are currently installed, including both `qml-module-qtquick-controls` and `qml-module-qtquick-controls2`

**Comment by muesli** [comment]
Which Ubuntu version is that? Sounds like it may be older than 2.5?

**Comment by Yowlen** [comment]
Ubuntu 18.04 LTS

**Comment by muesli** [comment]
Ah sorry, just saw your edit on the previous comment. I'll try and lower the dependency for the QtQuick Controls. I think the lowest dependency we can get away with is actually Qt 5.9.

**Comment by muesli** [comment]
Ok, should be fixed in 23baddb. Thanks for the feedback!
