### ISSUE TITLE
telephant doesn't run on unprivileged user

### ISSUE THREAD

**Issue by bionade24** [muesli/telephant#44]
```
panic: operation not permitted

goroutine 1 [running, locked to thread]:
main.init.2()
        /home/oskar/.cache/pikaur/build/telephant-git/src/gopath/src/github.com/muesli/telephant/notifications.go:15 +0x68
```
With run it as root, everything works. 
I used the AUR package: https://aur.archlinux.org/packages/telephant-git/

**Comment by muesli** [comment]
I don't think this has anything to do with privileges. Apparently it fails to initialize the notification system and the panic is voluntary. I've changed it to simply print out an error on console for now in 5532064.
