### ISSUE TITLE
Add text in compose window explaining drag-and-drop media upload functionality

### ISSUE THREAD

**Issue by Yowlen** [muesli/telephant#47]
I was actually unaware of the ability to upload images via drag-and-drop functionality until I saw another issue report pertaining to it. Having a little bit of text below the line in the compose window explaining the feature like GitHub does in these compose windows would be extremely helpful because the feature isn't documented anywhere else, and the best way is to have it documented right there imo.

**Comment by muesli** [comment]
Fixed in master.
