### ISSUE TITLE
Add file chooser for media upload

### ISSUE THREAD

**Issue by Yowlen** [muesli/telephant#48]
This is a complement issue report to #47, but since it's technically a different feature, I'm giving it its own issue report.

Some people prefer the drag-and-drop method, but others, such as myself, are more used to clicking a button and selecting a file that way. I believe you're planning on mobile builds too, judging by the readme saying mobile builds are untested atm, so if they're to ever have media upload functions, this will be required since Android doesn't do drag-and-drop.

**Comment by muesli** [comment]
Added in master.
