### ISSUE TITLE
Impossible to open posts with images but no text

### ISSUE THREAD

**Issue by Yowlen** [muesli/telephant#50]
Any posts containing images, but without any text are impossible to expand into conversation view.

Mastodon's webapp has this issue too, but they have a dropdown menu with an "Expand this status" option to get around it. Meanwhile, in mobile apps such as Tusky, tapping in the empty margins (i.e. below the avatar & to the left of the picture or on the right side of the picture) opens it up, so that could be a solution here too. I find this route much more intuitive than adding a dropdown menu item anyway.

**Comment by muesli** [comment]
For now the conversation view will only open when clicking the timestamp. I'm aware this isn't ideal, will look for a better solution.

**Comment by muesli** [comment]
I guess as such the actual issue is fixed though, as you can now open them.
