### ISSUE TITLE
Replying with lesser privacy than parent post

### ISSUE THREAD

**Issue by fynngodau** [muesli/telephant#57]
For example, when replying to a followers-only post or even direct message, the account's default privacy status will be used anyhow. This is generally unexpected and undesired behaviour, especially considering Telephant does not display the privacy status of a message and doesn't allow configuring it.

**Comment by muesli** [comment]
You're right, privacy settings aren't implemented yet. It's rather high up my todo-list, though. Thanks for filing this issue to keep track of it!

**Comment by muesli** [comment]
Fixed by #64.
